print('======DESAFIO 01======')
nome = input('Qual é o seu nome?')
print('Seja Bem Vindo Lucas ! É um prazer te conhecer !')
idade = input('Quantos anos vc tem?')
print('Uau!')
game = input('Qual é seu jogo favorito?')
print('Sem dúvidas esse é um dos que eu mais gosto! Vc tem muito bom gosto amigo.')
